import { Movie } from 'src/types/types';

export const movies: Movie[] = [
  {
    "id": "tt1234567",
    "title": "The Electric State",
    "poster": "https://upload.wikimedia.org/wikipedia/en/d/d7/The_Electric_State_poster.jpg",
    "release_date": "2025-03-14",
    "description": "In a post-apocalyptic world, an orphaned teenager and her robot companion embark on a journey to find her missing brother.",
    "actors": ["Millie Bobby Brown", "Chris Pratt", "Ke Huy Quan"],
    "director": "Anthony Russo, Joe Russo",
    "genres": ["Science Fiction", "Adventure"],
    "rating": 6.2
  },
  {
    "id": "tt2345678",
    "title": "Carry-On",
    "poster": "https://upload.wikimedia.org/wikipedia/en/d/d0/Carry_On_film_poster.jpg",
    "release_date": "2024-12-13",
    "description": "A TSA agent is blackmailed into allowing a dangerous package through security on Christmas Eve.",
    "actors": ["Taron Egerton", "Jason Bateman", "Sofia Carson"],
    "director": "Jaume Collet-Serra",
    "genres": ["Thriller", "Action"],
    "rating": 7.5
  },
  {
    "id": "tt3456789",
    "title": "To Catch a Killer",
    "poster": "https://upload.wikimedia.org/wikipedia/en/d/d1/ToCatch_A_KillerPoster.png",
    "release_date": "2025-01-20",
    "description": "A young FBI agent is recruited to help profile and track down a serial killer.",
    "actors": ["Shailene Woodley", "Ben Mendelsohn"],
    "director": "Damián Szifron",
    "genres": ["Crime", "Thriller"],
    "rating": 6.8
  },
  {
    "id": "tt4567890",
    "title": "The Life List",
    "poster": "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Life_List_poster.jpg",
    "release_date": "2025-02-14",
    "description": "A woman embarks on a journey to complete her late mother's bucket list, discovering herself along the way.",
    "actors": ["Sofia Carson"],
    "director": "Vanessa Parise",
    "genres": ["Romance", "Drama"],
    "rating": 7.0
  },
  {
    "id": "tt5678901",
    "title": "Plankton: The Movie",
    "poster": "https://upload.wikimedia.org/wikipedia/en/1/15/Plankton_The_Movie_poster.jpg",
    "release_date": "2025-03-07",
    "description": "Plankton's plans for world domination are thwarted when his computer wife, Karen, takes charge.",
    "actors": ["Mr. Lawrence", "Tom Kenny", "Bill Fagerbakke"],
    "director": "Dave Needham",
    "genres": ["Animation", "Comedy", "Musical"],
    "rating": 7.2
  },
  {
    "id": "tt6789012",
    "title": "Fear Street: Prom Queen",
    "poster": "\thttps://upload.wikimedia.org/wikipedia/en/3/3a/Fear_street_prom_queen_poster.jpg",
    "release_date": "2025-05-23",
    "description": "A series of murders disrupts a high school prom, and a group of teens must uncover the killer's identity.",
    "actors": ["India Fowler", "Suzanna Son", "Fina Strazza"],
    "director": "Matt Palmer",
    "genres": ["Horror", "Mystery"],
    "rating": 6.5
  },
  {
    "id": "tt7890123",
    "title": "Jewel Thief: The Heist Begins",
    "poster": "https://upload.wikimedia.org/wikipedia/en/a/ab/Jewel_Thief_%E2%80%93_The_Heist_Begins_poster.jpg",
    "release_date": "2025-04-25",
    "description": "A master thief plans an elaborate heist to steal a priceless jewel, facing unexpected challenges.",
    "actors": ["Saif Ali Khan", "Jaideep Ahlawat", "Nikita Dutta"],
    "director": "Kookie Gulati, Robbie Grewal",
    "genres": ["Action", "Thriller"],
    "rating": 6.9
  },
  {
    "id": "tt8901234",
    "title": "Atlas",
    "poster": "https://upload.wikimedia.org/wikipedia/en/f/f4/Atlas_2024_film_poster.png",
    "release_date": "2025-05-24",
    "description": "In a bleak future where AI is a threat, a soldier teams up with a robot to save humanity.",
    "actors": ["Jennifer Lopez", "Simu Liu", "Sterling K. Brown"],
    "director": "Brad Peyton",
    "genres": ["Science Fiction", "Action"],
    "rating": 6.4
  },
  {
    "id": "tt9012345",
    "title": "Lift",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Lift_2024_poster.webp/250px-Lift_2024_poster.webp.png",
    "release_date": "2024-01-12",
    "description": "A master thief and his crew try to pull off an impossible heist at 40,000 feet.",
    "actors": ["Kevin Hart", "Gugu Mbatha-Raw", "Vincent D'Onofrio"],
    "director": "F. Gary Gray",
    "genres": ["Action", "Comedy", "Crime"],
    "rating": 6.1
  },
  {
    "id": "tt9123456",
    "title": "Rebel Moon – Part Two: The Scargiver",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/Rebel_Moon_%E2%80%93_Part_Two_The_Scargiver_poster.jpg/250px-Rebel_Moon_%E2%80%93_Part_Two_The_Scargiver_poster.jpg",
    "release_date": "2025-04-19",
    "description": "The people of Veldt fight for their survival as they face an overwhelming imperial force.",
    "actors": ["Sofia Boutella", "Djimon Hounsou", "Ed Skrein"],
    "director": "Zack Snyder",
    "genres": ["Science Fiction", "Fantasy", "Action"],
    "rating": 5.7
  },
  {
    "id": "tt9234567",
    "title": "Damsel",
    "poster": "https://upload.wikimedia.org/wikipedia/en/f/f5/Damsel_2024_poster2.jpg",
    "release_date": "2024-03-08",
    "description": "A young woman discovers she's been offered as a sacrifice to a dragon and must fight for survival.",
    "actors": ["Millie Bobby Brown", "Angela Bassett", "Robin Wright"],
    "director": "Juan Carlos Fresnadillo",
    "genres": ["Fantasy", "Adventure", "Drama"],
    "rating": 6.3
  },
  {
    "id": "tt9345678",
    "title": "Code 8: Part II",
    "poster": "https://upload.wikimedia.org/wikipedia/en/4/45/Code_eight_part_II_poster.jpg",
    "release_date": "2024-02-28",
    "description": "A teenager with superpowers is on the run from a corrupt police force.",
    "actors": ["Robbie Amell", "Stephen Amell", "Sirena Gulamgaus"],
    "director": "Jeff Chan",
    "genres": ["Science Fiction", "Action", "Drama"],
    "rating": 6.0
  },
  {
    "id": "tt9456789",
    "title": "Spaceman",
    "poster": "https://upload.wikimedia.org/wikipedia/en/2/28/Spaceman_%282024_film%29_poster.jpg",
    "release_date": "2024-03-01",
    "description": "An astronaut on a solo mission discovers a mysterious creature that helps him understand his past.",
    "actors": ["Adam Sandler", "Carey Mulligan", "Paul Dano"],
    "director": "Johan Renck",
    "genres": ["Drama", "Science Fiction"],
    "rating": 5.9
  },
  {
    "id": "tt9567890",
    "title": "The Kitchen",
    "poster": "https://upload.wikimedia.org/wikipedia/en/e/ec/The_Kitchen_%28film%29_poster.jpg",
    "release_date": "2024-01-19",
    "description": "In a dystopian future London, a father and son fight to survive in a broken system.",
    "actors": ["Kano", "Jedaiah Bannerman", "Hope Ikpoku Jr"],
    "director": "Daniel Kaluuya, Kibwe Tavares",
    "genres": ["Drama", "Science Fiction"],
    "rating": 6.2
  },
  {
    "id": "tt9678901",
    "title": "Leave the World Behind",
    "poster": "https://upload.wikimedia.org/wikipedia/en/2/2d/Leave_the_World_Behind_film_poster.png",
    "release_date": "2023-12-08",
    "description": "A family's vacation is disrupted when two strangers arrive, bringing news of a mysterious cyberattack.",
    "actors": ["Julia Roberts", "Mahershala Ali", "Ethan Hawke"],
    "director": "Sam Esmail",
    "genres": ["Thriller", "Drama", "Mystery"],
    "rating": 6.7
  },
  {
    "id": "tt9789012",
    "title": "Nyad",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Nyad_film_poster.jpg/250px-Nyad_film_poster.jpg",
    "release_date": "2023-11-03",
    "description": "The inspirational true story of marathon swimmer Diana Nyad, who sets out to swim from Cuba to Florida at age 60.",
    "actors": ["Annette Bening", "Jodie Foster", "Rhys Ifans"],
    "director": "Elizabeth Chai Vasarhelyi, Jimmy Chin",
    "genres": ["Biography", "Drama", "Sport"],
    "rating": 7.0
  },
  {
    "id": "tt9890123",
    "title": "The Killer",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/The_Killer_2023_poster.jpg/220px-The_Killer_2023_poster.jpg",
    "release_date": "2023-11-10",
    "description": "After a fateful near-miss, an assassin battles his employers — and himself — on an international manhunt.",
    "actors": ["Michael Fassbender", "Tilda Swinton", "Charles Parnell"],
    "director": "David Fincher",
    "genres": ["Action", "Crime", "Drama"],
    "rating": 6.8
  },
  {
    "id": "tt9901234",
    "title": "May December",
    "poster": "https://upload.wikimedia.org/wikipedia/en/2/21/May_December_poster.jpeg",
    "release_date": "2023-12-01",
    "description": "An actress prepares for a role based on a woman's tabloid past, leading to a complex power dynamic.",
    "actors": ["Natalie Portman", "Julianne Moore", "Charles Melton"],
    "director": "Todd Haynes",
    "genres": ["Drama", "Romance"],
    "rating": 7.1
  },
  {
    "id": "tt9912345",
    "title": "Society of the Snow",
    "poster": "https://upload.wikimedia.org/wikipedia/en/7/76/Society_of_the_Snow_poster.jpg",
    "release_date": "2023-12-22",
    "description": "Based on the true story of the 1972 Andes flight disaster and the survivors' harrowing experience.",
    "actors": ["Enzo Vogrincic", "Matías Recalt", "Agustín Pardella"],
    "director": "J. A. Bayona",
    "genres": ["Drama", "History", "Survival"],
    "rating": 7.9
  },
  {
    "id": "tt9923456",
    "title": "Reptile",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Reptile_film_poster.png/220px-Reptile_film_poster.png",
    "release_date": "2023-09-29",
    "description": "A hardened detective uncovers disturbing truths while investigating a young real estate agent's murder.",
    "actors": ["Benicio del Toro", "Justin Timberlake", "Alicia Silverstone"],
    "director": "Grant Singer",
    "genres": ["Crime", "Drama", "Mystery"],
    "rating": 6.6
  },
  {
    "id": "tt9934567",
    "title": "Pain Hustlers",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Pain_hustlers_film_poster.jpg/250px-Pain_hustlers_film_poster.jpg",
    "release_date": "2023-10-27",
    "description": "Liza dreams of a better life for her daughter and gets caught up in a pharmaceutical scandal.",
    "actors": ["Emily Blunt", "Chris Evans", "Catherine O'Hara"],
    "director": "David Yates",
    "genres": ["Drama", "Crime"],
    "rating": 6.3
  },
  {
    "id": "tt9945678",
    "title": "Fair Play",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Fair_play_2023poster.png/250px-Fair_play_2023poster.png",
    "release_date": "2023-10-06",
    "description": "An unexpected promotion at a cutthroat hedge fund pushes a young couple to the edge.",
    "actors": ["Phoebe Dynevor", "Alden Ehrenreich", "Eddie Marsan"],
    "director": "Chloe Domont",
    "genres": ["Thriller", "Drama"],
    "rating": 6.5
  },
  {
    "id": "tt9967890",
    "title": "Family Switch",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Family_switch_poster.jpg/250px-Family_switch_poster.jpg",
    "release_date": "2023-11-30",
    "description": "A family experiences a massive body-swap chaos during a cosmic alignment, leading to unexpected bonding.",
    "actors": ["Jennifer Garner", "Ed Helms", "Emma Myers"],
    "director": "McG",
    "genres": ["Comedy", "Family", "Fantasy"],
    "rating": 5.7
  },
  {
    "id": "tt9978901",
    "title": "Rustin",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/9/91/RUSTIN_poster.jpg/250px-RUSTIN_poster.jpg",
    "release_date": "2023-11-17",
    "description": "The story of Bayard Rustin, a key figure in the U.S. civil rights movement and organizer of the 1963 March on Washington.",
    "actors": ["Colman Domingo", "Chris Rock", "Glynn Turman"],
    "director": "George C. Wolfe",
    "genres": ["Biography", "Drama", "History"],
    "rating": 7.1
  },
  {
    "id": "tt9989012",
    "title": "Love at First Sight",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Love_at_first_sight_2023.jpeg/250px-Love_at_first_sight_2023.jpeg",
    "release_date": "2023-09-15",
    "description": "After a chance meeting on a flight, two strangers begin to question the odds of fate and true love.",
    "actors": ["Haley Lu Richardson", "Ben Hardy", "Rob Delaney"],
    "director": "Vanessa Caswill",
    "genres": ["Romance", "Drama"],
    "rating": 6.8
  },
  {
    "id": "tt9990123",
    "title": "You People",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/7/75/You_People_Film_Poster.jpg/250px-You_People_Film_Poster.jpg",
    "release_date": "2023-01-27",
    "description": "A new couple faces cultural clashes, generational differences, and awkward family interactions.",
    "actors": ["Jonah Hill", "Lauren London", "Eddie Murphy"],
    "director": "Kenya Barris",
    "genres": ["Comedy", "Romance"],
    "rating": 5.5
  },
  {
    "id": "tt9991123",
    "title": "The Out-Laws",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/6/62/The_Out_Laws_poster.png/220px-The_Out_Laws_poster.png",
    "release_date": "2023-07-07",
    "description": "A straight-laced bank manager suspects his in-laws may be infamous outlaws after his bank is robbed.",
    "actors": ["Adam Devine", "Pierce Brosnan", "Ellen Barkin"],
    "director": "Tyler Spindel",
    "genres": ["Action", "Comedy", "Crime"],
    "rating": 5.4
  },
];
